<?php echo $this->getChildHtml('topHeaderUsp') ?>
<div class="header-container">
    <div class="header">
		<div class="row">
			<div class="col-sm-4">
				<p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
			</div>
			<div class="col-sm-8">
				<?php echo $this->getChildHtml('store_language') ?>
				<?php echo $this->getChildHtml('topLinks') ?>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-4">
				<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
					<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
				</a>      
			</div>
			<div class="col-sm-4">
				<?php echo $this->getChildHtml('topSearch') ?>
			</div>
			<div class="col-sm-4">
					
					<?php echo $this->getChildHtml('topcart'); ?>
			</div>
		</div>		
		<?php echo $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
