<div class="header-top">
	<div class="container">
		<div class="row">
			<div class="col-sm-3"><i class="icon-caret-right"></i> Kostenloser Versand</div>
			<div class="col-sm-3"><i class="icon-caret-right"></i> Kauf auf Rechnung</div>
			<div class="col-sm-3"><i class="icon-caret-right"></i> 40 Tage Rückgaberecht</div>
			<div class="col-sm-3 text-right"><i class="icon-caret-right"></i> Kostenlose Hotline  0800 / 5678 111</div>
		</div>
	</div>
</div>
