<div class="dashboard">
    <div class="page-header">
        <h1><?php echo $this->__('My Dashboard') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="box-account box-info ">
		<div class="page-header">
			<h2 class="panel-title"><?php echo $this->__('Account Information') ?></h2>
		</div>
		<div>
			<?php /* Extensions placeholder */ ?>
			<?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
			<?php echo $this->getChildHtml('info') ?>
			<?php echo $this->getChildHtml('address') ?>
		</div>
    </div>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
