<div class="block block-account panel panel-default">
    <div class="block-title panel-heading">
        <h2 class="panel-title"><?php echo $this->__('My Account'); ?></h2>
    </div>
	<ul class="nav">
		<?php $_links = $this->getLinks(); ?>
		<?php $_index = 1; ?>
		<?php $_count = count($_links); ?>
		<?php foreach ($_links as $_link): ?>
			<?php $_last = ($_index++ >= $_count); ?>
			<?php if ($this->isActive($_link)): ?>
				<li class="active current<?php echo ($_last ? ' last' : '') ?>"><a><strong><?php echo $_link->getLabel() ?></strong></a></li>
			<?php else: ?>
				<li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
			<?php endif; ?>
		<?php endforeach; ?>
	</ul>
</div>
