<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login">
    <div class="page-header">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
		<!-- Magento 1.8.1.0 start -->
		<?php echo $this->getBlockHtml('formkey'); ?>
		<!-- Magento 1.8.1.0 end -->
        <div class="row">
            <div class="col-sm-6 new-users">
                <div class="content panel panel-default">
                    <div class="panel-heading"><h2 class="panel-title"><?php echo $this->__('New Customers') ?></h2></div>
					<div class="panel-body clearfix">
						<p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
						<button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button btn btn-success pull-right" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
					</div>
				</div>
            </div>
            <div class="col-sm-6 registered-users">
                <div class="content panel panel-default">
                    <div class="panel-heading"><h2 class="panel-title"><?php echo $this->__('Registered Customers') ?></h2></div>
                    <div class="panel-body">
						<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
						<ul class="form-list list-unstyled form-horizontal">
							<li>
								<label for="email" class="required control-label"><?php echo $this->__('Email Address') ?><em>*</em></label>
								<div class="input-box">
									<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email form-control" title="<?php echo $this->__('Email Address') ?>" />
								</div>
							</li>
							<li>
								<label for="pass" class="required control-label"><?php echo $this->__('Password') ?><em>*</em></label>
								<div class="input-box">
									<input type="password" name="login[password]" class="input-text required-entry validate-password form-control" id="pass" title="<?php echo $this->__('Password') ?>" />
								</div>
							</li>
							<?php echo $this->getChildHtml('form.additional.info'); ?>
							<?php echo $this->getChildHtml('persistent.remember.me'); ?>
						</ul>
						<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
						<p class="required"><?php echo $this->__('* Required Fields') ?></p>
						
						<div class="clearfix">
							<a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
							<button type="submit" class="button btn btn-success pull-right" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
						</div>
					</div>
                </div>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
