<?php
/**
 * One page checkout payment methods
 *
 * @see Mage_Checkout_Block_Onepage_Payment_Methods
 */
?>

<?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
?>
<?php
    foreach ($methods as $_method):
        $_code = $_method->getCode();
?>
    <div class="row<?php if($this->getSelectedMethodCode()==$_code): ?> active<?php endif; ?>">
        <div class="col-sm-3">
            <label for="p_method_<?php echo $_code ?>">
                <?php if(!$oneMethod): ?>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="" />
                <?php else: ?>
                    <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="" /></span>
                    <?php $oneMethod = $_code; ?>
                <?php endif; ?>

                <?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?>
                <?php echo $this->getMethodLabelAfterHtml($_method) ?>
            </label>
        </div>
        <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
        <div class="col-sm-9">
            <?php echo $html; ?>
        </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();

<?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
<?php endif; ?>

jQuery( document ).ready(function($) {

jQuery('input[name^=payment]:checked').parent().parent().parent().addClass('active');

$('input[name^=payment]').click(function(el)
{
$('.checkout-onepage-payment .row').removeClass('active');
$(el.target).parent().parent().parent().addClass('active');
});

});
</script>
