<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>


<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?
$current_category = Mage::registry('current_category');
if($current_category->getLevel() == 2): ?>
<div class="category_teaser">
	<div class="name"><? echo $_category->getName(); ?></div>
	<div class="picture">
		<?php if($_imgUrl): ?>
		    <?php echo $_imgHtml ?>
		<?php endif; ?>
	</div>
</div>
<? endif; ?>

<? echo $this->getChildHtml('catalog_bestseller') ?>
<? echo $this->getChildHtml('category_teaser') ?>

<div class="page-header">
	<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
<?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>