<div class="page-title page-header">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset panel panel-default">
        <?php echo $this->getBlockHtml('formkey')?>
        <div class="panel-heading">
			<h2 class="legend panel-title"><?php echo $this->__('Newsletter Subscription') ?></h2>
		</div>
		<div class="panel-body">
			<ul class="form-list list-unstyled">
				<li class="control">
					<label for="subscription">
						<input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="" />
						<?php echo $this->__('General Subscription') ?>
					</label>
				</li>
				<?php /* Extensions placeholder */ ?>
				<?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
			</ul>
		</div>
    </div>
    <div class="buttons-set">
        <p class="back-link pull-left btn btn-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button btn btn-success pull-right"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
