<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-header">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<div class="row">
	<div class="col-sm-offset-3 col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">
			    <h2 class="panel-title"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
			</div>
			<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" class="">
			    <div class="panel-body ">
			    	<div class="form-group">
	                    <label for="name" class="required control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
	                    <div class="input-box">
	                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry form-control" type="text" />
	                    </div>
	               </div>
	                <div class="form-group">
	                    <label for="email" class="required control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
	                    <div class="input-box">
	                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email form-control" type="text" />
	                    </div>
			        </div>
			        <div class="form-group">
			                <label for="telephone" class="control-label"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
			                <div class="input-box">
			                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text form-control" type="text" />
			                </div>
			        </div>
			        <div class="form-group">
			                <label for="comment" class="required control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
			                <div class="input-box">
			                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text form-control" cols="5" rows="3"></textarea>
			                </div>
			        </div>
			    </div>
			    <div class="panel-footer">
			    	<div class="pull-left">
			    		<p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
			    	</div>
				    <div class="buttons-set text-right">
				        
				        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
				        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button btn btn-primary"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
				    </div>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>