<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @package    Billpay
 * @author 	   Jan Wehrs <jan.wehrs@billpay.de>
 * @copyright  Copyright (c) 2009 Billpay GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var Billpay_Block_PayLater_Form $this
 */
?>
<div id="paylater_container" style="width: auto"><noscript>Please enable Javascript</noscript></div>
<?php /** Billpay_Block_PayLater $this */ ?>
<script type="text/javascript">
    var bpyPayLater = {
        selector: '#paylater_container',
        options: {
            apiKey      : '<?php echo $this->getApiKey(); ?>', // merchant specific api key
            form        : '#co-payment-form',                  // payment form to append data to
            country     : '<?php echo $this->getBillingAddressCountryIso3(); ?>',
            countryIso2 : '<?php echo $this->getBillingAddressCountryIso2(); ?>',
            currency    : '<?php echo $this->getCurrencyCode(); ?>',
            lang        : 'de',
            baseAmount  : '<?php echo $this->getCalculationBaseAmount(); ?>',     // order amount excl. shipping
            orderAmount : '<?php echo $this->getOrderAmount(); ?>',               // order amount incl. shipping
            live        : <?php echo $this->isTesting() == false ? 1 : 0; ?>,          // required for the agb link
            userIdentifier : '<?php echo $this->getUserIdentifier(); ?>',              // session id of the customer for dfp
            mode        : <?php echo $this->getVisualMode(); ?>,

            customer: {
                name      : '<?php echo $this->getFullName(); ?>',  // placeholder for the bank account holder
                dob       : '<?php echo $this->getCustomerDob(); ?>',                                   // if null we display a dob input field
                gender    : '<?php echo $this->getCustomerGender(); ?>', // if null we display a gender select field
                phone     : '<?php echo $this->getCustomerPhone(); ?>'
            },

            inputNames: {
                accountHolder : 'payment[<?php echo $this->getMethodCode(); ?>_account_holder]',
                accountIBAN   : 'payment[<?php echo $this->getMethodCode(); ?>_account_number]',
                accountBIC    : 'payment[<?php echo $this->getMethodCode(); ?>_sort_code]',
                gender        : 'payment[<?php echo $this->getMethodCode(); ?>_gender]',
                dob           : 'payment[<?php echo $this->getMethodCode(); ?>_dob]',
                phone         : 'payment[<?php echo $this->getMethodCode(); ?>_phone]',
                toc           : 'payment[<?php echo $this->getMethodCode(); ?>_tcaccepted]',
                instalments   : 'payment[billpay_instalments]',
                duration      : 'payment[billpay_duration]',
                feeTotal      : 'payment[billpay_fee_total]',
                totalAmount   : 'payment[billpay_total_amount]'
            }
        }
    };
    try { window.bpyPayLater = bpyPayLater; initPayLater() } catch(e) {}
</script>