<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<div class="row">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="col-sm-6">
		<div class="panel panel-default login-form">
			<div class="panel-heading">
				<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?>
			</div>
			<div class="panel-body">
				<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
					<p><?php echo $this->__('Register with us for future convenience:') ?></p>
				<?php else: ?>
					<p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
					<?php echo $this->__('Register with us for future convenience:') ?></p>
					<ul>
						<li><?php echo $this->__('Fast and easy check out') ?></li>
						<li><?php echo $this->__('Easy access to your order history and status') ?></li>
					</ul>
				<?php endif; ?>
				<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
					<ul class="form-list  list-unstyled">
						<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
						<li class="control radio">
							<label for="login:guest">
								<input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST || $this->getQuote()->getCheckoutMethod()=='' ): ?> checked="checked"<?php endif; ?> />
								<?php echo $this->__('Checkout as Guest') ?>
							</label>
						</li>
						<?php endif; ?>
						<li class="control radio">
							<label for="login:register">
								<input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> />
								<?php echo $this->__('Register') ?>
							</label>
						</li>
					</ul>
					<h4><?php echo $this->__('Register and save time!') ?></h4>
					<p><?php echo $this->__('Register with us for future convenience:') ?></p>
					<ul class="ul">
						<li><?php echo $this->__('Fast and easy check out') ?></li>
						<li><?php echo $this->__('Easy access to your order history and status') ?></li>
					</ul>
				<?php else: ?>
					<input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
				<?php endif; ?>
				
				<hr />
				
				<div class="buttons-set clearfix">
					<?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
						<button id="onepage-guest-register-button" type="button" class="button btn btn-success pull-right" onclick="checkout.setMethod();"><?php echo $this->__('Continue') ?></button>
					<?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
						<button id="onepage-guest-register-button" type="button" class="button btn btn-success pull-right" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><?php echo $this->__('Register') ?></button>
					<?php else: ?>
						<form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
							<button id="onepage-guest-register-button" type="submit" class="button btn btn-success pull-right"><?php echo $this->__('Register') ?></button>
						</form>
					<?php endif; ?>
				</div>
				
			</div>
		</div>
    </div>
    <div class="col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<?php echo $this->__('Login') ?>
			</div>
			<div class="panel-body">
				<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
				<form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" class="form-horizontal">
				<fieldset>
					<!-- Magento 1.8.1.0 start -->
					<?php echo $this->getBlockHtml('formkey'); ?>
					<!-- Magento 1.8.1.0 end -->
					<strong><?php echo $this->__('Already registered?') ?></strong><br /><br />
					<p><?php echo $this->__('Please log in below:') ?></p>
					<ul class="form-list list-unstyled">
						<li class="form-group">
							<label for="login-email" class="required col-sm-5 control-label"><?php echo $this->__('Email Address') ?><em>*</em></label>
							<div class="input-box col-sm-7">
								<input type="text" class="input-text required-entry validate-email form-control" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
							</div>
						</li>
						<li class="form-group">
							<label for="login-password" class="required col-sm-5 control-label"><?php echo $this->__('Password') ?><em>*</em></label>
							<div class="input-box col-sm-7">
								<input type="password" class="input-text required-entry form-control" id="login-password" name="login[password]" />
							</div>
						</li>
						<?php echo $this->getChildHtml('form.additional.info'); ?>
						<?php echo $this->getChildHtml('persistent.remember.me'); ?>
					</ul>
					<input name="context" type="hidden" value="checkout" />
					
					<p class="required clearfix"><?php echo $this->__('* Required Fields') ?></p>
				</fieldset>
				</form>
				
				<hr />
				
				<div class="buttons-set clearfix">
					
					<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
					<button type="submit" class="button btn btn-success pull-right" onclick="onepageLogin(this)"><?php echo $this->__('Login') ?></button>
				</div>
			</div>	
		</div>		
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
