<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="thumbnail">
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
	<a href="#" data-toggle="modal" data-slide-to="0" data-target="#media-popup">
    <?php
        $_img = '<img id="image" class="img-responsive" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?></a>
</p>
<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img class="img-responsive" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
</div>
<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
<?php $i=1; foreach ($this->getGalleryImages() as $_image): ?>
    <div class="more-view-item thumbnail text-center">
    	<a href="#" data-toggle="modal" data-slide-to="<?=$i?>" data-target="#media-popup" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        <? /*<a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a> */?>
    </div>
<?php $i++; endforeach; ?>
	<div class="clearfix"></div>
</div>
<?php endif; ?>

<!-- Modal -->
  <div class="modal fade" id="media-popup" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
        </div>
        <div class="modal-body">
          <div id="media-popup-carousel" class="carousel slide">
			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			  	<div class="item active">
			  		<? echo $_helper->productAttribute($_product, $_img, 'image'); ?>
		        	<div class="carousel-caption">
				        <?php #echo $this->htmlEscape($this->getImageLabel()) ?>
				    </div>
		        </div>
			  <?php if (count($this->getGalleryImages()) > 0): ?>
			  	<?php foreach ($this->getGalleryImages() as $_image): ?>
		        <div class="item">
		        	<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(800); ?>" height="800" width="800" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
		        	<div class="carousel-caption">
				        <?php #echo $this->htmlEscape($_image->getLabel()) ?>
				    </div>
		        </div>
		    	<?php endforeach; ?>
		      <?php endif; ?>
			  </div>
			
			  <!-- Controls -->
			  <a class="left carousel-control" href="#media-popup-carousel" data-slide="prev">
			    <span class="icon-prev"></span>
			  </a>
			  <a class="right carousel-control" href="#media-popup-carousel" data-slide="next">
			    <span class="icon-next"></span>
			  </a>
			</div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  
<script>
jQuery(document).ready(function ($) {
  	$('#media-popup-carousel').carousel({
  		interval:false
  	});
});
</script>

