<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
<hr />
<div class="crosssell">
	<div class="lead">
		<?php echo $this->__('Based on your selection, you may be interested in the following items:') ?>
	</div>
	<div id="crosssell-products-list" class="row">
	<? $i = 1; ?>
	<?php foreach ($this->getItems() as $_item): ?>
		<div class="col-sm-4">
			<div class="item media thumbnail">
				<a class="product-image pull-left" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>">
					<img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(150); ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
				</a>
				<div class="product-details media-body">
					<div class="product-name media-heading"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></div>
					<?php echo $this->getPriceHtml($_item, true) ?>
					<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn btn-success" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
					
					<? /*
					<div class="btn-group btn-group-vertical pull-right">
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist btn btn-xs"><?php echo $this->__('Add to Wishlist') ?></a>
						<?php endif; ?>
						<?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
							<a href="<?php echo $_compareUrl ?>" class="link-compare btn btn-xs"><?php echo $this->__('Add to Compare') ?></a>
						<?php endif; ?>
					</div> */ ?>
				</div>
			</div>
		</div>
		<?  if($i == $this->getMaxItems()) break; ?>
	<?php $i++; endforeach; ?>
	</div>
</div>
<?php endif; ?>
