<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>
<ul class="layered_nav_filter_list list-unstyled">
	<?php foreach ($this->getItems() as $_item): ?>
			<li><?php if ($_item->getCount() > 0): ?>
				<a class="" href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
					<?php echo $_item->getLabel() ?>
					<?php if ($this->shouldDisplayProductCount()): ?>
						<span class="">(<?php echo $_item->getCount() ?>)</span>
					<?php endif; ?>
				</a>				
			<?php else: ?>
				<span class=""><?php echo $_item->getLabel() ?></span>
			<?php endif; ?></li>
	<?php endforeach ?>
</ul>
