<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
	<ol class="layered_nav_state_list list-unstyled">
		<?php foreach ($_filters as $_filter): ?>
			<li class="">
				<span><?php echo $this->__($_filter->getName()) ?>:</span> 
				<strong><?php echo $this->stripTags($_filter->getLabel()) ?></strong>
				
				<?php
					$clearLinkUrl = $_filter->getClearLinkUrl();
					if ($clearLinkUrl):
				?>
					<a class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Previous') ?>"><?php echo $this->__('Previous') ?></a>
					<a class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>"><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
				<?php else: ?>
					<a class="glyphicon glyphicon-remove pull-right label label-danger" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>"></a>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ol>
<?php endif; ?>
