<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <div class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <div class="thumbnail clearfix item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image col-sm-4">
				<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(350); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			</a>
            <?php // Product description ?>
            <div class="product-shop col-sm-8 caption">
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				
				<div class="row">
					<div class="product-name col-sm-12">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
					</div>
					<div class="desc std col-sm-7">
						<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
					</div>
					<div class=" col-sm-5">
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn btn-success btn-cart btn-block" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="glyphicon glyphicon-shopping-cart"></span> <?php echo $this->__('Add to Cart') ?></button>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						
						<?php if($this->helper('wishlist')->isAllow()):?><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist btn btn-xs btn-link"><?php echo $this->__('Add to Wishlist') ?></a></li><?php endif; ?>
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><a href="<?php echo $_compareUrl ?>" class="link-compare btn btn-xs btn-link"><?php echo $this->__('Add to Compare') ?></a><?php endif; ?>
					</div>
				</div>			
				
				
				<?php if($_product->getRatingSummary()): ?>
					<?php echo $this->getReviewsSummaryHtml($_product) ?>
				<?php endif; ?>
			</div>
        </div>
    <?php endforeach; ?>
    </div>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>
    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $_image_resize = 250; ?>
    <div class="row">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <div class="products-grid">
        <?php endif ?>
            <div class="col-sm-12 col-md-4 col-lg-<?php echo round(12/$_columnCount); ?> item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<div class="thumbnail">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
						<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_image_resize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
					</a>
					<div class="caption">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-name">
							<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
						</a>
						
						<div class="manufacturer">
						<? if($_product->hasData('manufacturer')): ?>
							<? echo $_product->getAttributeText('manufacturer') ?>
						<? endif; ?>
						</div>
						
						<div class="actions">							
							<?php if($_product->isSaleable()): ?>
								<? /*<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-success" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
									<span class="glyphicon glyphicon-shopping-cart"></span> <?php echo $this->__('Add to Cart') ?>
								</button> */?>
								<p class="availability in-stock text-success"><span><?php echo $this->__('In stock') ?></span></p>
							<?php else: ?>
								<p class="availability out-of-stock text-danger"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
		
							<?php /*if($this->helper('wishlist')->isAllow()):?><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist btn btn-xs btn-link"><?php echo $this->__('Add to Wishlist') ?></a></li><?php endif;*/ ?>
							<?php /*if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><a href="<?php echo $_compareUrl ?>" class="link-compare btn btn-xs btn-link"><?php echo $this->__('Add to Compare') ?></a><?php endif;*/ ?>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<div class="pull-left">
									<div class="delivery-time text-muted">
									<? if($_product->hasData('delivery_time') && $_product->getData('delivery_time') !=''): ?>
										<?php echo $this->__('Delivery time') ?>:
										<?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getData('delivery_time'), 'delivery_time') ?>
									<? endif; ?>
									</div>
									
									<?php if($_product->getRatingSummary()): ?>
										<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<?php endif; ?>
								</div>
								<div class="price-container pull-right text-right">
									<?php echo $this->getPriceHtml($_product, true) ?>
								</div>
							</div>
						</div>
					</div>
				</div>
            </div>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </div>
        <?php endif ?>
    <?php endforeach ?>
    </div>
    <script>/*
	jQuery(document).ready(function ($) {
		var imageHeight = <?php echo $_image_resize ?>;
		var heights = $(".products-grid .item").map(function (){ return $(this).height(); }).get();
		maxHeight = Math.max.apply(null, heights)
		
		if(maxHeight <= imageHeight){
			 maxHeight = maxHeight + imageHeight;
		}
	   
	    $('.products-grid .item .thumbnail').css('height',maxHeight+'px');
	});*/
	</script>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
</div>
<div class="toolbar-bottom text-right">
        <?php #echo $this->getToolbarHtml() ?>
        <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_bottom.phtml')->toHtml(); ?> 
    </div>
<?php endif; ?>