<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        
	    <div class="row">
		    <div class="col-sm-12">
	            <?php echo $this->getChildHtml('alert_urls') ?>
		    </div>
	    </div>
		
		<div class="row">
			<div class="product-img-box col-sm-6 col-md-6 col-lg-7">
	            <?php echo $this->getChildHtml('media') ?>
	        </div>
		
	        <div class="product-shop col-sm-6 col-md-6 col-lg-5">
	        	
		        <div class="product-name">
		            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
		        </div>
		        
		        <? if($_product->hasData('manufacturer')): ?>
				<div class="manufacturer"><? echo $_product->getAttributeText('manufacturer') ?></div>
				<? endif; ?>
				
				<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
	        	<?php echo $this->getChildHtml('product_type_data') ?>
	        	<div class="priceinfo text-muted">Inkl. <? echo $_product->getData('tax_percent'); ?>% MwSt., zzgl. Versandkosten</div>
	        	
	        	<?php echo $this->getTierPriceHtml() ?>
	            
	            <?php echo $this->getChildHtml('extrahint') ?>
	            
	            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
	                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
	            <?php endif;?>
	
	            <?php if (!$this->hasOptions()):?>
	                <div class="add-to-box">
	                    <?php if($_product->isSaleable()): ?>
	                        <?php echo $this->getChildHtml('addtocart') ?>
	                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
	                        
	                        <?php endif; ?>
	                    <?php endif; ?>
	                    <?php echo $this->getChildHtml('addto') ?>
	                </div>
	                <?php echo $this->getChildHtml('extra_buttons') ?>
	            <?php elseif (!$_product->isSaleable()): ?>
	                <div class="add-to-box">
	                    <?php echo $this->getChildHtml('addto') ?>
	                </div>
	            <?php endif; ?>
	
				<?php if ($this->canEmailToFriend()): ?>
	            	<p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
	            <?php endif; ?>
	        </div>
        </div>
        
        <div class="row">
        	<div class="col-sm-12">
        		<?php echo $this->getChildHtml('other');?>
        	</div>
        </div>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
        	<div class="after-info-col">
        	<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        	</div>
        <?php endif;?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>


    <div class="product-collateral">
		<div class="row">
			<div class="col-sm-12">
				<ul class="nav nav-tabs" data-tabs="tabs">
					<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
						<li><a href="#tab-content-<?php echo $alias ?>" data-toggle="tab"><?php echo $this->getChildData($alias, 'title') ? $this->escapeHtml($this->getChildData($alias, 'title')) : $alias ?></a></li>
					<?php endforeach;?>
				</ul>
				 
				<div class="tab-content">
					<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
					<div class="tab-pane" id="tab-content-<?php echo $alias ?>">
						<div class="panel panel-default">
							<div class="panel-body">
								<?php echo $html; ?>
							</div>
						</div>
					</div>
					<?php endforeach;?>
				</div>
				<script>
				jQuery(document).ready(function ($) {
					$(".product-collateral .nav-tabs").tab();
					$('.product-collateral .nav-tabs a:first').tab('show');
				});
				</script>
			</div>
			<? /*
			<div class="col-sm-4">
				<div class="panel">
					<div class="panel-body">
						<? echo $this->getChildHtml('product_options_wrapper_bottom'); ?>
					</div>
				</div>
			</div>	*/ ?>
			
		</div>
		
    
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
