<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons page-header">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info panel panel-default">
    <dt class="panel-heading"><?php echo $this->__('About This Order:') ?>
    	
    		<p class="order-date pull-right"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
    </dt>
    <dd class="panel-body">
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $_link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>

<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box row">
    <div class="col-1 col-sm-6">
        <div class="box panel panel-default">
            <div class="box-title panel-heading">
                <?php echo $this->__('Shipping Address') ?>
            </div>
            <div class="box-content panel-body">
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2 col-sm-6">
        <div class="box panel panel-default">
            <div class="box-title panel-heading">
            	<?php echo $this->__('Shipping Method') ?>
            </div>
            <div class="box-content panel-body">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box row">
    <div class="col-1 col-sm-6">
        <div class="box panel panel-default">
            <div class="box-title panel-heading">
            	<?php echo $this->__('Billing Address') ?>
            </div>
            <div class="box-content panel-body">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2 col-sm-6">
        <div class="box box-payment panel panel-default">
            <div class="box-title panel-heading">
            	<?php echo $this->__('Payment Method') ?>
            </div>
            <div class="box-content panel-body">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
