<div class="box panel panel-default">
	<div class="box-title panel-heading">
		<h3 class="panel-title" >
			<?php echo $this->__('Address Book') ?>
			<a class="btn btn-default btn-xs pull-right" href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
		</h3>		
	</div>
	<div class="box-content panel-body clearfix row">
		<div class="col-sm-6">
			<h4><?php echo $this->__('Default Billing Address') ?></h4>
			<address>
				<?php echo $this->getPrimaryBillingAddressHtml() ?><br />
				<a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
			</address>
		</div>
		<div class="col-sm-6">
			<h4><?php echo $this->__('Default Shipping Address') ?></h4>
			<address>
				<?php echo $this->getPrimaryShippingAddressHtml() ?><br />
				<a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
			</address>
		</div>
	</div>
</div>
