<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */?>
<?php $_product = $this->getProduct() ?>
<?php $_helper = $this->helper('catalog/output'); ?>


<div class="row">
	<div class="col-sm-4">
<?php if ($_product->isAvailable()): ?>
    <p class="availability in-stock text-success"><span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock text-danger"><span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>
	</div>
	<div class="col-sm-8">
		<?php echo $this->getChildHtml('product_type_data_extra') ?>
	</div>
</div>


<?php if ($_product->getShortDescription()):?>
    <div class="short-description">
        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
    </div>
<?php endif;?>

<?php echo $this->getPriceHtml($_product) ?>
