<?php
/**
 * Last order sidebar
 *
 * @see Mage_Sale_Block_Reorder_Sidebar
 */
?>
<?php $_items = $this->getItems()?>
<?php if($_items): ?>
<div class="block block-reorder panel panel-default">
    <div class="block-title panel-heading">
        <strong><span><?php echo $this->__('My Orders') ?></span></strong>
    </div>
    <form method="post" action="<?php echo $this->getFormActionUrl() ?>" id="reorder-validate-detail">
        <div class="block-content panel-body">
            <p class="block-subtitle"><?php echo $this->__('Last Ordered Items') ?></p>
            <ol id="cart-sidebar-reorder" class="list-unstyled">
            <?php $_showAddButtonFlag = false ?>
            <?php foreach ($_items as $_item): ?>
                <li class="item input-group">
                	<span class="input-group-addon">
                    <?php if ($this->isItemAvailableForReorder($_item)): ?>
                        <?php $_showAddButtonFlag = true ?>
                        <input type="checkbox" name="order_items[]" id="reorder-item-<?php echo $_item->getId() ?>" value="<?php echo $_item->getId() ?>" title="<?php echo $this->__('Add to Cart') ?>" class="checkbox validate-one-required-by-name" />
                        <script type="text/javascript">
                        //<![CDATA[
                            $('reorder-item-<?php echo $_item->getId() ?>').advaiceContainer = 'cart-sidebar-reorder-advice-container';
                        //]]>
                        </script>
                    <?php endif; ?>
                    </span>
                    <div class="product-name form-control"><a href="<?php echo $_item->getProduct()->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></div>
                    
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('cart-sidebar-reorder')</script>
            <div id="cart-sidebar-reorder-advice-container"></div>
            <div class="actions">
               
                <a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('View All'); ?></a>
            </div>
        </div>
        <div class="panel-footer">
        	<?php if ($_showAddButtonFlag): ?>
                <button type="submit" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn btn-warning btn-block"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php endif; ?>
        </div>
    </form>
</div>
<?php echo $this->getPagerHtml(); ?>
<script type="text/javascript">
//<![CDATA[
    var reorderFormDetail = new VarienForm('reorder-validate-detail');
//]]>
</script>
<?php endif ?>
