<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <li>
            <div class="input-box">
                <?php if ($this->getMethod()->getInfoText('infotext_checkout')): ?>
                    <?php echo $this->getMethod()->getInfoText('infotext_checkout') ?><br />
                <?php endif; ?>				
            </div>
        </li>
    </ul>
</fieldset>